package condorcet.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    WORKER_UPDATE,
	MANAG,
	SCHEDULE_UPDATE,
	SCHEDULE_DELETE,
	SCHEDULE_ADD,
	
    ADD_FLIGHT,
    DELETE_FLIGHT,
    GET_FLIGHT,
    GETALL_FLIGHT,
    UPDATE_FLIGHT,
    UPDATE_MARK,
    UPDATE_PASSENGER,
    CONDORCET,
}
